### ISSUE TITLE
Pagination for list of alumni and colleges.

### ISSUE THREAD

**Issue by rohansingh9001** [rohansingh9001/Smart-India-Hackathon-Web-Crawler#15]
The list of alumni may get very long!

We only want to show a certain number of alumni in the list.
The recommended number is 8-12.

Find a suitable number which suits the webpage while still being easy to navigate.

The rest of the users should be shown on a list of pages.

**Comment by Saptashrungi** [comment]
I am working on it.

**Comment by rohansingh9001** [comment]
Solved
