### ISSUE TITLE
Search Filter for Alumni

### ISSUE THREAD

**Issue by Saptashrungi** [rohansingh9001/Smart-India-Hackathon-Web-Crawler#6]
This issue requires django rest framework. On searching we should get proper filtered result.

**Comment by Saptashrungi** [comment]
I am already working on it.

**Comment by UmangSonika** [comment]
What is the problem with current searching technique?? I guess it's also getting perfect results!!!

**Comment by Saptashrungi** [comment]
Yes but there should be one search bar for all 4 of them.

**Comment by rohansingh9001** [comment]
Describe the problem more clearly.

**Comment by rohansingh9001** [comment]
Assigned to @Saptashrungi
